# Generated by Django 4.0.4 on 2022-04-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='country',
            field=models.CharField(choices=[('AS', 'Australia'), ('CN', 'Canada'), ('US', 'United States'), ('RU', 'Russia'), ('JP', 'Japan'), ('IN', 'India'), ('CH', 'China')], max_length=300),
        ),
    ]
