# Generated by Django 4.0.4 on 2022-04-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_feedback_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
