# Generated by Django 4.0.4 on 2022-04-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_feedback_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='thumbnail',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
